# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
